@startuml

interface Agent {
    +see(perception: Object): Promise
    +see(action: Object, args: Object): Promise
}
interface Mind {
    +see(perception: Object): Promise
}
interface IntelligentMind {
    +get(key: Object): Object
    +set(key: Object, value: Object)
}
class Ceed {
    mind: Mind
}
interface Action {
    +act(args: Object): Promise
    +getAgent(): Agent
    +setAgent(agent: Agent)
}
abstract AbstractAction {
 - agent: Agent
}
class NaiveMind {
    +seeBehavior: Action
    +getBehavior: Action
    +setBehavior: Action
    +actBehavior: Action
}


Mind <|-- IntelligentMind
IntelligentMind <|-- NaiveMind
Agent <|-- Ceed
Action <|-- AbstractAction

@enduml